name: stress_equals
description: Demonstrates how overriding equals puts stress on dart2js type inference
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
