name: stress_over_react
description: Try stressing over_react SSA code generation
version: 1.0.0

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  over_react:

dev_dependencies:
  react:
  w_flux:
  build_runner: 
  build_web_compilers: 
